### ISSUE TITLE
A pure jade wrapper for marko instead of gulp plugin?

### ISSUE THREAD

**Issue by laggingreflex** [kristianmandrup/jade-markoa#4]
Hi! I've recently gotten in to Marko and coming from Jade I can't let go of the syntax :)

But this seems to be a gulp plugin, yes? If so I was wondering would you be interested in a pure jade wrapper that provides a 1-to-1 functionality of Marko but for something like `.jade-marko` files? I whipped up a small such library for my own use: [jade-marko](https://github.com/laggingreflex/jade-marko). But as you can see it's very limited, it doesn't implement all of the functions, let alone the intricacies of jade and marko syntax collisions (which you seem to have solved beautifully btw). 

What would your thoughts be for such a library?

**Comment by kristianmandrup** [comment]
I'm no longer a developer. Feel free to do your own thing using this lib for inspiration... I've become totally disillusioned by the state of web dev and the slow progress being made to improve it!!!
